// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/13/2025, 10:58:05 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/plugins/**/*.{js,ts,mjs}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/composables/**/*.{js,ts,mjs}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/utils/**/*.{js,ts,mjs}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ghozimahdi/Projects/Project Website/tanahdijualjogja/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;